### ISSUE TITLE
agent does not exist

### ISSUE THREAD

**Issue by Ondrik8** [Ne0nd0g/merlin-agent#15]
### Prerequisite

* [ ] I have searched the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin-agent/issues)
* [ ] I have searched the [WIKI](https://merlin-c2.readthedocs.io/en/latest/index.html) and its [FAQ](https://merlin-c2.readthedocs.io/en/latest/quickStart/faq.html) page

### Environment Data

* Merlin Version:1.41
* Merlin Build:1.4.1
* Go Version:1.18
* GOPATH Environment Variable: /root/go/bin
* GOROOT Environment Variable:
* Operating System: debian

### Misc Information
![Screenshot_4](https://user-images.githubusercontent.com/59111771/163247039-d3adac34-c20d-459d-a502-82df1fd35ff8.png)

![Screenshot_3](https://user-images.githubusercontent.com/59111771/163246971-cc1c89ec-4dbc-4996-9afa-0865e7fa8d34.png)
![Screenshot_5](https://user-images.githubusercontent.com/59111771/163247500-cf112168-ab76-4ea8-ad22-683e9e2ce818.png)

**Comment by Ne0nd0g** [comment]
The server AND the agent must be built with the same garble seed. You can do this with `make windows-garble` for the Merlin server repository.

**Comment by Ondrik8** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/59111771/163247763-a58b6a6e-7852-45d3-8ab3-fdc0b96671ed.png)

**Comment by Ne0nd0g** [comment]
Have you built the server using the `garble` build target as well?

**Comment by Ondrik8** [comment]
no only agent build>garble

**Comment by Ne0nd0g** [comment]
OK. You must build the server using garble if you want it to work.

```
git clone https://github.com/Ne0nd0g/merlin
cd merlin
make linux-garble
```

**Comment by Ondrik8** [comment]
Ok, I'll test it now, thanks!

**Comment by Ne0nd0g** [comment]
Swing by the Slack channel if you want to chat more about it. https://bloodhoundgang.herokuapp.com/

**Comment by Ondrik8** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/59111771/163253203-0c7e1548-9d70-4c5d-9f07-ac5560bdfe10.png)
its Works)))

**Comment by Ne0nd0g** [comment]
I'm going to update the server so that it shows this message instead of the one you saw:
```
[!] there was an error decoding JWE payload message sent by an agent:
gob: type mismatch: no fields matched compiling decoder for Base

[i] BOTH the Merlin server AND agent must both be obfuscated with the same seed
```

**Comment by Ne0nd0g** [comment]
The output of the `sessions` command showed little information because after the agent completes authentication, it needs to wait for one more sleep cycle to send back all of its information.
