### ISSUE TITLE
Command output always fails to be sent properly after a failed connection

### ISSUE THREAD

**Issue by r00t0v3rr1d3** [Ne0nd0g/merlin-agent#16]
### Prerequisite

* [ x ] I have searched the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin-agent/issues)
* [ x ] I have searched the [WIKI](https://merlin-c2.readthedocs.io/en/latest/index.html) and its [FAQ](https://merlin-c2.readthedocs.io/en/latest/quickStart/faq.html) page

### Environment Data

* Merlin Version: 1.4.1
* Operating System: Kali Linux 

### Expected Behavior
- If a merlinAgent is unable to connect back to the merlinServer, but it has job results from previous commands, it should re-send the job results the next time the agent is able to connect again.

### Actual Behavior
- If, for whatever reason, a merlinAgent is unable to check-in, it does not properly put the job results back on its queue and resend later. I have witnessed in the code the section where it is SUPPOSED to be doing this properly, but it doesn't. On the server side, you will never receive the output of the commands you ran previously, you always receive the following message: "[!] Invalid: 20 is not a valid job type".

### Steps to Reproduce Behavior
- Easiest way to reproduce is with sub-interfaces or iptables. Ensure the sleep is long enough that you can have the agent check in and receive the tasking, then use iptables after that point to create a reject rule for the agent's return traffic to create at least one failed check-in, then disable the iptables rule and let the traffic flow properly. The sub-interfaces route - you can have the agent calling back to a sub-interface that you just bring up or down to simulate the failure to send the job results output the first time.

### Misc Information
- This actually happens pretty frequently in networks with high latency and packet loss and especially in competitive events like CCDC. This also causes really strange "ghosting" behavior in agents where right after the OPAQUE Auth, if the agent fails to send back the initial AgentInfo that is requested, the agent will never establish properly and the server seems to eternally send the agent 404's.

![merlin_resiliency1](https://user-images.githubusercontent.com/8229583/166256328-a5bd3bec-896e-44e2-a84a-c8bb592a6d79.png)
![merlin_resiliency2](https://user-images.githubusercontent.com/8229583/166256329-e064616f-1c1a-4c41-b97c-2ea56f04887b.png)

**Comment by Ne0nd0g** [comment]
Found the issue. The `jobHandler()` function was not handling `jobs.Results` which triggered the default case statement. The default case statement overwrote the job result with `Invalid: 20 is not a valid job type`. I added a case statement to put the job back into the `jobsOut` channel and this seems to have resolved everything.

**Comment by Ne0nd0g** [comment]
Did the same for the `jobs.AgentInfo` job type. It is important to note the last JWT provided by the server after successful OPAQUE authentication is scoped to 30 seconds. The server depends on the `AgentInfo` structure to correctly calculate the life of subsequent JWTs. Therefore, if more than 30 seconds have passed, the agent will be required to re-authenticate before it can successfully send the AgentInfo message back. The potential exists for the agent to exit after triggering the max failed checkin count (by design).
