### ISSUE TITLE
Why does the merlin-agent depend on the merlin？

### ISSUE THREAD

**Issue by yhy0** [Ne0nd0g/merlin-agent#2]
When I modified the code in Merlin, the main logic did not change, just changed some display, added fields to the agents/agents/Agent of merlin, why use agent, when communicating, display 404

Can you remove the dependencies on Merlin from the agent and separate the code from merlin
![Uploading image.png…]()

**Comment by Ne0nd0g** [comment]
The https://github.com/Ne0nd0g/merlin repository contains structures that are used in the agent code. I do not intend to remove the other repository as a dependency at this time.
