### ISSUE TITLE
Unable to compile Merlin Agent

### ISSUE THREAD

**Issue by breachlabs-org** [Ne0nd0g/merlin-agent#29]
### Prerequisite

* [x] I have searched the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin-agent/issues)
* [x] I have searched the [WIKI](https://merlin-c2.readthedocs.io/en/latest/index.html) and its [FAQ](https://merlin-c2.readthedocs.io/en/latest/quickStart/faq.html) page

### Environment Data

* Merlin Version: Latest
* Merlin Build: Latest
* Go Version: go version go1.20.3 linux/amd64
* GOPATH Environment Variable: GOROOT=$HOME/go
* GOROOT Environment Variable: PATH=$PATH:$GOROOT/bin
* Operating System: Ubuntu 23.04

### Expected Behavior

Expecting to compile the agent and not receive an error.

``` make windows ```

### Actual Behavior

See the error message, thanks
```
make windows
export GOOS=windows GOARCH=amd64;go build -trimpath -ldflags '-s -w -X "main.build=b2e84d8beea2d0dd87bc23f950de7842193cb28d" -X "github.com/Ne0nd0g/merlin-agent/agent.build=b2e84d8beea2d0dd87bc23f950de7842193cb28d" -X "main.protocol=h2" -X "main.url=https://127.0.0.1:443" -X "main.host=" -X "main.psk=merlin" -X "main.sleep=30s" -X "main.proxy=" -X "main.useragent=Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.85 Safari/537.36" -X "main.headers=" -X "main.skew=3000" -X "main.padding=4096" -X "main.killdate=0" -X "main.maxretry=7" -X "main.parrot=" -H=windowsgui -buildid=' -gcflags=all=-trimpath= -asmflags=all=-trimpath= -o bin/v1.6.5/b2e84d8beea2d0dd87bc23f950de7842193cb28d/merlinAgent-Windows-x64.exe ./main.go
# github.com/lucas-clemente/quic-go/internal/qtls
../../../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.30.0/internal/qtls/go120.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
make: *** [Makefile:78: windows] Error 1
```

**Comment by Ne0nd0g** [comment]
The error is showing that the code can't be compiled with go 1.20. You will need to use go 1.19 . I am aware of this and will be pushing an update in the next couple of weeks to resolve this. If you can't use go 1.19 right now, let me know and I'll develop a work around.

**Comment by breachlabs-org** [comment]
Hello, i have used the go 1.19 as mentioned and i was able to perform the compilation, my apologies the error message didn't make me think to use a previous version. Thanks!

**Comment by Ne0nd0g** [comment]
If you want to use a later version of Go, here is a quick work around. From the `merlin-agent` root directory, run these commands
```
sed -i 's/lucas-clemente/quic-go/g' go.mod clients/http/http.go
sed -i 's/quic-go v0.30.0/quic-go v0.38.1/g' go.mod
go get github.com/quic-go/quic-go
go get github.com/quic-go/quic-go/http3
make windows
```
