### ISSUE TITLE
Unable to satisfy the OPAQUE handshake

### ISSUE THREAD

**Issue by breachlabs-org** [Ne0nd0g/merlin-agent#30]
### Prerequisite

* [x] I have searched the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin-agent/issues)
* [x] I have searched the [WIKI](https://merlin-c2.readthedocs.io/en/latest/index.html) and its [FAQ](https://merlin-c2.readthedocs.io/en/latest/quickStart/faq.html) page

### Environment Data

Merlin Version: Latest
Merlin Build: Latest
Go Version: go version go1.20.3 linux/amd64
GOPATH Environment Variable: GOROOT=$HOME/go
GOROOT Environment Variable: PATH=$PATH:$GOROOT/bin
Operating System: Ubuntu 23.04

### Expected Behavior
Connect back from the agent

### Actual Behavior

Problems with the OPAQUE auth framework

```[!]there was an error performing OPAQUE User Registration:
there was an error sending the OPAQUE User Registration Initialization message to the server:
there was an error communicating with the server:
404
```

### Steps to Reproduce Behavior

used http,https,h2c,http3 listeners and i have been unable to get a reverse connection from an agent.

either manually compiled, or i used the provided agent, server, dll.

**Comment by Ne0nd0g** [comment]
Can you validate that the host the agent is running on and the server are using NTP and that there is not time skew between them? Can you also validate the PSK was the same for both the listener and the agent? Did you use Garble?

**Comment by breachlabs-org** [comment]
Hello, i was able to get a reverse connection based on the troubleshooting tips you gave me, again thank you for your help!
