### ISSUE TITLE
Process List Command Returns BUILTIN Group Name Instead of Username

### ISSUE THREAD

**Issue by Ne0nd0g** [Ne0nd0g/merlin-agent#9]
### Prerequisite

* [x] I have searched the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin-agent/issues)
* [x] I have searched the [WIKI](https://merlin-c2.readthedocs.io/en/latest/index.html) and its [FAQ](https://merlin-c2.readthedocs.io/en/latest/quickStart/faq.html) page

### Environment Data

* Merlin Version: v1.3.0

### Expected Behavior

That the output of the `ps` command on Windows will list the _user_ associated with the running process

### Actual Behavior

The `ps` command returns the group names starting with `BUILTIN` instead of the actual user name:

```
1896	1864	x64	BUILTIN\Administrators	explorer.exe
```

### Steps to Reproduce Behavior

Run the `ps` command.

### Misc Information

Agent was running on Server 2012R2

**Comment by r00t0v3rr1d3** [comment]
The sliver guys figured this out: https://github.com/BishopFox/sliver/pull/669/commits/ff503203e3ca6591501e532579ae339b34750f41
